repos:
  # Prevent commits to main/master
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: no-commit-to-branch
        args: [ '--branch', 'main', '--branch', 'master' ]
        fail_fast: true
      - id: check-toml
      - id: check-yaml
        # This limits the check-yaml to simply parse them for syntax.
        # Avoiding fully loading them, as that doesn't work with the !ENV tags etc.
        args: [ --unsafe ]
      - id: detect-private-key
      - id: check-added-large-files

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: [ '--fix' ]
      - id: ruff-format

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
    - id: detect-secrets
      name: Detect secrets
      description: Detects high entropy strings that are likely to be passwords.
      entry: detect-secrets-hook
      exclude: .cruft.json
      language: python
